name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nod-version: [12, 14, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/set-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependecies
        run: npm install

      - name: Run tests
        run: npm test
